# Currency Demo - Step 1: Namespaces
# WHAT: Creates namespace for MCP servers
# WHY:  Isolation for MCP tool servers
# HOW:  oc apply -f 01-namespaces.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: agent-sandbox
