# Currency Demo - Step 2: Currency MCP Server
# WHAT: Deploys the Currency MCP Server (provides get_exchange_rate tool)
# WHY:  MCP server that wraps frankfurter.app currency API
# HOW:  oc apply -f 02-currency-mcp-server.yaml
#
# This is the EXACT config working in the cluster.

---
apiVersion: v1
kind: Service
metadata:
  name: currency-mcp-server
  namespace: mcp-test
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: currency-mcp-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-mcp-server
  namespace: mcp-test
  labels:
    app: currency-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-mcp-server
  template:
    metadata:
      labels:
        app: currency-mcp-server
      annotations:
        # IMPORTANT: Disable Istio sidecar - server needs direct external access
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: mcp-server
          image: quay.io/rbrhssa/currency-mcp-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - mountPath: /.cache
              name: cache
      volumes:
        - emptyDir: {}
          name: cache
      imagePullSecrets:
        - name: quay-pull-secret
