# Currency Demo - Step 6: Currency Agent with Kata
# WHAT: Deploys Currency Agent using Kagenti Agent CRD with Kata VM
# WHY:  Demonstrates VM isolation for agent workloads
# HOW:  oc apply -f 06-currency-agent.yaml
#
# PREREQUISITE: Create gemini-api-key secret first:
#   oc create secret generic gemini-api-key \
#     --from-literal=GOOGLE_API_KEY='your-key' -n agent-sandbox

---
apiVersion: agent.kagenti.dev/v1alpha1
kind: Agent
metadata:
  name: currency-agent
  namespace: agent-sandbox
  labels:
    app: currency-agent
spec:
  description: ADK Currency Agent running in Kata VM for secure isolation
  replicas: 1
  servicePorts:
    - name: http
      port: 10000
      protocol: TCP
      targetPort: 10000
  imageSource:
    image: quay.io/rbrhssa/currency-agent:latest
  podTemplateSpec:
    spec:
      # Kata VM isolation
      runtimeClassName: kata
      containers:
        - name: agent
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-api-key
                  key: GOOGLE_API_KEY
            # Routes through gateway proxy → OPA enforcement
            - name: MCP_SERVER_URL
              value: http://currency-mcp-gateway.agent-sandbox.svc.cluster.local:8080/mcp
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
      imagePullSecrets:
        - name: quay-pull-secret

