# Kagenti Secrets Template
# ========================
# Copy this file to /tmp/.secrets.yaml and fill in your values:
#   cp scripts/.secrets_template.yaml /tmp/.secrets.yaml
#   vim /tmp/.secrets.yaml
#
# Then run the install script:
#   ./scripts/install-kagenti.sh

secrets:
  # GitHub credentials (required for AgentBuild to clone repos)
  githubUser: YOUR_GITHUB_USERNAME
  githubToken: "ghp_your_github_personal_access_token"
  
  # LLM API key (required for agents to call LLM)
  # Use either OpenAI or Gemini API key
  openaiApiKey: "your_gemini_or_openai_api_key"
  
  # Container registry credentials (optional, for pushing images)
  # quayUser: YOUR_QUAY_USERNAME
  # quayToken: "your_quay_encrypted_password"

